server:
  port: '5002'

zipkin:
  base-url: http://localhost:9411

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: 'true'
    service-url:
      defaultZone: http://localhost:7001/eureka
    fetch-registry: 'true'

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  application:
    name: Product-Service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/product-service-db
    username: postgres
    password: Simform@123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show-sql: false
    hibernate:
      ddl-auto: update